[tools]
# Binaries
atuin = "latest"
yazi = "latest"
bat = "latest"
bottom = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
just = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"
mold = "latest"
neovim = "latest"
node = "lts"
python = "latest"

[env]
# Global Variables
EDITOR = "nvim"
VISUAL = "nvim"
PAGER = "bat"
LANG = "en_US.UTF-8"
LD_LIBRARY_PATH = "/usr/local/lib:${LD_LIBRARY_PATH:-}"

# Performance/System Tweaks
RUSTFLAGS = "-C link-arg=-fuse-ld=mold"

# Custom Paths
# PATH = "/home/gsmith-alvarez/.local/bin:$PATH"

[settings]
env_shell_expand = true
