[tools]
# Binaries
ripgrep = "latest"
starship = "latest"
zoxide = "latest"
mold = "latest"
neovim = "latest"

#tools
atuin = "latest"
yazi = "latest"
bat = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
just = "latest"
typos = "latest"
glow = "latest"
carapace = "latest"

#js
node = "lts"
oxlint = "latest"
# oxfmt = "latest" #not yet supported

#python
python = "latest"
uv = "latest"
ruff = "latest"

#lua
lua = "latest"
stylua = "latest"
lua-language-server = "latest"

#Microcontrollers
arduino-cli = "latest"

#Languages of interest
rust = "latest"
go = "latest"
zig = "latest"

[env]
# Global Variables
EDITOR = "nvim"
VISUAL = "nvim"
PAGER = "bat"
LANG = "en_US.UTF-8"
LD_LIBRARY_PATH = "/usr/local/lib:${LD_LIBRARY_PATH:-}"
GOPATH = "{{env.HOME}}/.local/share/go"

# Performance/System Tweaks
RUSTFLAGS = "-C link-arg=-fuse-ld=mold"

# Custom Paths
"PATH" = "{{env.HOME}}/.local/share/go/bin:{{env.PATH}}"

[settings]
env_shell_expand = true
